version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: mango_postgres
    environment:
      POSTGRES_DB: mango
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mango_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mango_app
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/mango?sslmode=disable
    networks:
      - mango_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  mango_network:
    driver: bridge