version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    container_name: mango_postgres
    environment:
      POSTGRES_DB: mango
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mango"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s
    networks:
      - mango_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mango_app
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=mango
      - DB_SSLMODE=disable
    networks:
      - mango_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  mango_network:
    driver: bridge